resolver: ./cardano-sl.yaml
packages:
- .

extra-deps:
- git: https://github.com/input-output-hk/cardano-sl
  commit: 308acc08720785966a4c5aed9235b063208f0fcd
  subdirs:
    - acid-state-exts
    - binary
    - binary/test
    - chain
    - chain/test
    - client
    - cluster
    - core
    - core/test
    - crypto
    - crypto/test
    - db
    - infra
    - lib
    - mnemonic
    - networking
    - node
    - node-ipc
    - util
    - util/test
    - utxo
    - x509
